# Generated by Django 3.1 on 2023-03-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='cuisines',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisines',
            field=models.ManyToManyField(blank=True, null=True, related_name='restaurants_cuisines', to='restaurants.Cuisines', verbose_name='Cuisines'),
        ),
    ]
