# Generated by Django 3.1 on 2023-04-28 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_auto_20230316_1648'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
