# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0  # pick a git hash / tag to point to
    hooks:
      - id: detect-private-key
      - id: check-merge-conflict
      - id: check-ast

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint app/
        language: system
        types: [python]
        args: ["--disable=E0307"]
        
      - id: flake8
        name: flake8
        entry: flake8 app
        language: system
        types: [python]
