# Generated by Django 3.1 on 2023-06-26 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0007_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Total price')),
                ('status', models.CharField(choices=[('in_processing', 'in_processing'), ('delivered', 'delivered'), ('completed', 'completed'), ('canceled', 'canceled')], default='in_processing', max_length=50, verbose_name='Status')),
                ('address', models.CharField(max_length=200, verbose_name='address delivery')),
                ('costumer_name', models.CharField(max_length=100, verbose_name='costumer name')),
                ('costumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costumer', to=settings.AUTH_USER_MODEL, verbose_name='costumer')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='restaurants.restaurant', verbose_name='Restaurant')),
            ],
        ),
    ]
