# Generated by Django 3.1 on 2023-07-06 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_review'),
        ('orders', '0002_cart_cartitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='dishes',
        ),
        migrations.AddField(
            model_name='cart',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='restaurants.restaurant', verbose_name='restaurant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitems',
            name='dish',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart_item_dishes', to='restaurants.dishes', verbose_name='dish'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='orders.cart', verbose_name='Cart'),
        ),
    ]
