# Generated by Django 3.1 on 2023-07-17 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20230717_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order',
            new_name='cart',
        ),
    ]
