# Generated by Django 3.1 on 2023-07-27 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0006_auto_20230717_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='costumer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='costumer_name',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='accounts.user', verbose_name='customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default=1, max_length=100, verbose_name='customer name'),
            preserve_default=False,
        ),
    ]
