# Generated by Django 3.1 on 2023-08-28 09:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20230811_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
