# Generated by Django 3.1 on 2023-09-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_cart_cart_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='intent_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
